# Usando uma imagem do Python leve
FROM python:3.11-slim

# Atualizando o sistema e instalando pacotes necessários
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    gcc \
    libpq-dev \
    && rm -rf /var/lib/apt/lists/*

# Criar o diretório de trabalho no contêiner
WORKDIR /app

# Copiar os arquivos necessários para dentro do contêiner
COPY requirements.txt .

# Instalar as dependências do Python
RUN pip install --no-cache-dir -r requirements.txt

# Copiar o restante dos arquivos do projeto
COPY . .

# Expôr a porta onde a aplicação vai rodar
EXPOSE 8000

# Definir o comando para rodar a aplicação
CMD ["uvicorn", "api:app", "--host", "0.0.0.0", "--port", "8000"]
